package com.jio.jiotalkie.adapter;

import android.view.View;
import android.widget.FrameLayout;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.TextView;

import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.emoji2.widget.EmojiEditText;
import androidx.emoji2.widget.EmojiTextView;
import androidx.recyclerview.widget.RecyclerView;

import com.google.android.gms.maps.MapView;
import com.jio.jiotalkie.dispatch.R;

public class ChatViewHolder extends RecyclerView.ViewHolder {
    ImageView seekbar;
    ImageView seekbar2;
    ImageView image;
    ImageView image2;
    CardView imageCard;
    RelativeLayout imageCard2;
    TextView target;
    TextView target2;
    EmojiTextView text;
    EmojiTextView text2;
    TextView time;
    TextView time2;
    View view;
    RelativeLayout audioLayout;
    RelativeLayout audioLayout2;
    RelativeLayout messageBoxWithTime;
    RelativeLayout messageBoxWithTime2;
    ImageButton buttonPlay;
    ImageButton buttonPlay2;
    ImageButton buttonDownloadAudio;
    ImageButton buttonDownloadAudio2;
    LinearLayout triangle;
    LinearLayout triangle2;
    LinearLayout box;
    RelativeLayout relativeLayout;
    ConstraintLayout constraintLayout;
    RelativeLayout linearLayout;
    TextView userProfile;
    TextView dateDivider;
    MapView mapView;
    MapView mapView2;
    ConstraintLayout sosSentMessageLayout;
    ConstraintLayout sosReceivedMessageLayout;
    TextView sosSenderName;
    ImageView sosBatteryStatusImage;
    TextView sosBatteryStatusText;
    ImageView sosSenderOnlineStatus;
    ImageButton sosAudioPlayButton;
    ImageButton sosSentAudioPlayButton;
    ImageView sosAnimationImageView;
    ImageView sosSentAnimationImageView;
    TextView sosTimerText;
    TextView sosSentTimerText;
    TextView sosLocationText;
    TextView sosSentLocationText;
    TextView sosSentBatteryText;
    TextView sosReceiveNavigationImage;
    ProgressBar mediaPlayerLoadingBarSentSOS;
    ProgressBar mediaPlayerLoadingBarSentAudio;
    ProgressBar mediaPlayerLoadingBarReceiveSOS;
    ProgressBar mediaPlayerLoadingBarReceiveAudio;
    ProgressBar progressBarImageSend;
    TextView sosSentTimeText;
    TextView sosReceiveTimeText;
    ImageButton buttonDownloadAudioSos;
    ImageButton buttonDownloadAudioSos2;
    RelativeLayout playerViewLayoutReceive;
    RelativeLayout playerViewLayoutSend;
    ImageView videoDownloadSendButton;
    ImageView videoDownloadReceiveButton;
    ImageView videoPlaySendButton;
    ImageView videoPlayReceiveButton;
    ImageView videoImageSend;
    ImageView videoImageReceive;
    ProgressBar progressBarVideoSend;
    ProgressBar progressBarVideoReceive;
    ImageView messageStatusIcon;
    RelativeLayout documentViewReceiver;
    ImageView documentImageViewReceiver;
    TextView documentExtensionReceiver;
    TextView documentFileNameReceiver;
    ImageButton docDownloadReceiverBtn;
    ProgressBar progressBarDocReceiver;

    RelativeLayout documentViewSender;
    ImageView documentImageViewSender;
    TextView documentExtensionSender;
    TextView documentFileNameSender;
    ImageButton docDownloadSendBtn;
    ProgressBar progressBarDocSend;
    TextView audioDurationReceiver;
    TextView audioDurationSender;
    FrameLayout chatItemFrame;

    ChatViewHolder(View itemView) {
        super(itemView);
        messageBoxWithTime = (RelativeLayout)itemView.findViewById(R.id.message_box_with_time);
        messageBoxWithTime2 = (RelativeLayout)itemView.findViewById(R.id.message_box_with_time2);
        userProfile = (TextView)itemView.findViewById(R.id.user_row_talk_highlight);
        linearLayout = (RelativeLayout)itemView.findViewById(R.id.message_with_pfp);
        relativeLayout = (RelativeLayout)itemView.findViewById(R.id.parent_relative);
        target = (TextView)itemView.findViewById(R.id.list_chat_item_target);
        text = (EmojiTextView) itemView.findViewById(R.id.list_chat_item_text);
        time = (TextView)itemView.findViewById(R.id.list_chat_item_time);
        target2 = (TextView)itemView.findViewById(R.id.list_chat_item_target2);
        text2 = (EmojiTextView)itemView.findViewById(R.id.list_chat_item_text2);
        time2 = (TextView)itemView.findViewById(R.id.list_chat_item_time2);
        audioLayout = (RelativeLayout)itemView.findViewById(R.id.list_chat_item_audio);
        audioDurationReceiver = (TextView)itemView.findViewById(R.id.audio_duration_receiver);
        buttonPlay = (ImageButton)itemView.findViewById(R.id.list_chat_item_play);
        audioLayout2 = (RelativeLayout)itemView.findViewById(R.id.list_chat_item_audio2);
        buttonPlay2 = (ImageButton)itemView.findViewById(R.id.list_chat_item_play2);
        audioDurationSender = itemView.findViewById(R.id.send_audio_duration);
        buttonDownloadAudio = (ImageButton)itemView.findViewById(R.id.list_chat_item_download);
        buttonDownloadAudio2 = (ImageButton)itemView.findViewById(R.id.list_chat_item_download2);
        seekbar = (ImageView) itemView.findViewById(R.id.list_chat_item_seekbar);
        seekbar2 = (ImageView)itemView.findViewById(R.id.list_chat_item_seekbar2);
        box = (LinearLayout)itemView.findViewById(R.id.list_chat_item_box);
        triangle = (LinearLayout)itemView.findViewById(R.id.list_chat_item_triangle);
        triangle2 = (LinearLayout)itemView.findViewById(R.id.list_chat_item_triangle2);
        constraintLayout = (ConstraintLayout)itemView.findViewById(R.id.chat_item_constraint);
        image = (ImageView)itemView.findViewById(R.id.list_chat_item_image);
        imageCard = (CardView)itemView.findViewById(R.id.list_chat_image_card);
        image2 = (ImageView)itemView.findViewById(R.id.list_chat_item_image2);
        imageCard2 = (RelativeLayout)itemView.findViewById(R.id.list_chat_image_card2);
        mapView = itemView.findViewById(R.id.mapview);
        mapView2 = itemView.findViewById(R.id.mapview2);
        sosSentMessageLayout = (ConstraintLayout) itemView.findViewById(R.id.sos_sent_msg);
        sosReceivedMessageLayout = (ConstraintLayout) itemView.findViewById(R.id.sos_received_msg);
        //SOS Layout
        sosSenderName = (TextView) sosReceivedMessageLayout.findViewById(R.id.sos_sender_name);
        sosBatteryStatusImage = (ImageView) sosReceivedMessageLayout.findViewById(R.id.battery_status);
        sosBatteryStatusText = (TextView) sosReceivedMessageLayout.findViewById(R.id.battery_status_text);
        sosSenderOnlineStatus = (ImageView) sosReceivedMessageLayout.findViewById(R.id.iv_online_status);
        sosAudioPlayButton = sosReceivedMessageLayout.findViewById(R.id.iv_sos_play);
        sosAnimationImageView =(ImageView) sosReceivedMessageLayout.findViewById(R.id.iv_sos_receiver_wave);
        sosSentAnimationImageView =(ImageView) sosSentMessageLayout.findViewById(R.id.iv_sos_receiver_wave1);
        sosTimerText = (TextView) sosReceivedMessageLayout.findViewById(R.id.timer_text);
        sosSentTimerText = (TextView) sosSentMessageLayout.findViewById(R.id.timer_text1);
        sosLocationText = (TextView) sosReceivedMessageLayout.findViewById(R.id.location);
        sosSentLocationText = (TextView) sosSentMessageLayout.findViewById(R.id.location1);
        sosSentAudioPlayButton = itemView.findViewById(R.id.iv_sos_play1);
        sosSentBatteryText = (TextView) sosSentMessageLayout.findViewById(R.id.battery_status_text1);
        sosReceiveNavigationImage = (TextView) sosReceivedMessageLayout.findViewById(R.id.sos_navigate_chat);
        sosSentTimeText = (TextView) sosSentMessageLayout.findViewById(R.id.time_textView1);
        sosReceiveTimeText = (TextView) sosReceivedMessageLayout.findViewById(R.id.time_textView);
        mediaPlayerLoadingBarSentSOS = sosSentMessageLayout.findViewById(R.id.mediaPlayerLoadingBarSentSOS);
        mediaPlayerLoadingBarReceiveSOS = sosReceivedMessageLayout.findViewById(R.id.mediaPlayerLoadingBarReceiveSOS);
        mediaPlayerLoadingBarSentAudio = itemView.findViewById(R.id.mediaPlayerLoadingBarSentAudio);
        mediaPlayerLoadingBarReceiveAudio = itemView.findViewById(R.id.mediaPlayerLoadingBarReceivedAudio);
        buttonDownloadAudioSos = (ImageButton)sosReceivedMessageLayout.findViewById(R.id.iv_sos_download);
        buttonDownloadAudioSos2 = (ImageButton)sosSentMessageLayout.findViewById(R.id.iv_sos_download1);
        playerViewLayoutReceive = itemView.findViewById(R.id.player_view_layout_receive);
        playerViewLayoutSend = itemView.findViewById(R.id.player_view_layout_send);
        videoDownloadSendButton=itemView.findViewById(R.id.video_download_send_button);
        videoDownloadReceiveButton=itemView.findViewById(R.id.video_download_receive_button);
        videoPlaySendButton=itemView.findViewById(R.id.video_play_send_button);
        videoPlayReceiveButton=itemView.findViewById(R.id.video_play_receive_button);
        videoImageSend = itemView.findViewById(R.id.video_image_send);
        videoImageReceive = itemView.findViewById(R.id.video_image_receive);
        progressBarVideoReceive = itemView.findViewById(R.id.progress_bar_video_receive);
        progressBarVideoSend = itemView.findViewById(R.id.progress_bar_video_send);
        documentViewReceiver = itemView.findViewById(R.id.doc_view_rec_rl);
        docDownloadReceiverBtn = itemView.findViewById(R.id.doc_download_rec_imgBtn);
        progressBarDocReceiver = itemView.findViewById(R.id.progress_bar_doc_receive);
        documentImageViewReceiver = itemView.findViewById(R.id.doc_txt_file_rec_imgView);
        documentExtensionReceiver = itemView.findViewById(R.id.doc_file_mimetype_rec_txtView);
        documentFileNameReceiver = itemView.findViewById(R.id.doc_file_name_rec_txtView);
        documentViewSender = itemView.findViewById(R.id.doc_view_send_rl);
        documentImageViewSender = itemView.findViewById(R.id.doc_txt_file_send_imgView);
        documentExtensionSender = itemView.findViewById(R.id.doc_file_mimetype_send_txtView);
        documentFileNameSender = itemView.findViewById(R.id.doc_file_name_send_txtView);
        messageStatusIcon = (ImageView) itemView.findViewById(R.id.delivery_status);
        view = itemView;
        dateDivider = (TextView) itemView.findViewById(R.id.date_divider);
        docDownloadSendBtn = itemView.findViewById(R.id.doc_download_send_imgBtn);
        progressBarDocSend = itemView.findViewById(R.id.progress_bar_doc_send);
        progressBarImageSend = itemView.findViewById(R.id.progress_bar_image_send);
        chatItemFrame = itemView.findViewById(R.id.chat_item_frame);
    }
}

